[package]
name = "thbp"
version = "0.0.1"
entrypoint = "blockly_hathi.typ"
authors = ["Bjoern Schilberg"]
repository = "https://github.com/bjoernschilberg/thbp"

description = "Package for rendering Abbozza! Hathi World code blocks"
license = "MIT"
